/* Generated By:JJTree: Do not edit this line. ASTAdditivePlus.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTAdditivePlus extends SimpleNode {
  public ASTAdditivePlus(int id) {
    super(id);
  }

  public ASTAdditivePlus(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9aa2d5af6b9432aca9cbfcba6b958b45 (do not edit this line) */
