/* Generated By:JJTree: Do not edit this line. ASTAdditiveMinus.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTAdditiveMinus extends SimpleNode {
  public ASTAdditiveMinus(int id) {
    super(id);
  }

  public ASTAdditiveMinus(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bef4a10e6c1e48d9c6144fef97758632 (do not edit this line) */
