/* Generated By:JJTree: Do not edit this line. ASTExclusiveOR.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTExclusiveOR extends SimpleNode {
  public ASTExclusiveOR(int id) {
    super(id);
  }

  public ASTExclusiveOR(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=543158da0f2d0781b2f2bb0d17b875cf (do not edit this line) */
