/* Generated By:JJTree: Do not edit this line. ASTFloatConst.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTFloatConst extends SimpleNode {
  public ASTFloatConst(int id) {
    super(id);
  }

  public ASTFloatConst(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=317cbcebd6130bf8de0ff6a38d4df508 (do not edit this line) */
