/* Generated By:JJTree: Do not edit this line. ASTForUpdateStatement.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTForUpdateStatement extends SimpleNode {
  public ASTForUpdateStatement(int id) {
    super(id);
  }

  public ASTForUpdateStatement(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=caac590e056a9b8796d21b11d9357499 (do not edit this line) */
