/* Generated By:JJTree: Do not edit this line. ASTInclusiveOR.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTInclusiveOR extends SimpleNode {
  public ASTInclusiveOR(int id) {
    super(id);
  }

  public ASTInclusiveOR(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5f9dbe35acfded156aa7e55c56dea035 (do not edit this line) */
