/* Generated By:JJTree: Do not edit this line. ASTIntegerConst.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTIntegerConst extends SimpleNode {
  public ASTIntegerConst(int id) {
    super(id);
  }

  public ASTIntegerConst(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c3e058cd01528501bf03e3978fb5a030 (do not edit this line) */
