/* Generated By:JJTree: Do not edit this line. ASTLogicalAND.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTLogicalAND extends SimpleNode {
  public ASTLogicalAND(int id) {
    super(id);
  }

  public ASTLogicalAND(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2a13f66c8545d7be35ed5133ac00493 (do not edit this line) */
