/* Generated By:JJTree: Do not edit this line. ASTLogicalOR.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTLogicalOR extends SimpleNode {
  public ASTLogicalOR(int id) {
    super(id);
  }

  public ASTLogicalOR(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=297663ca2e51f5e2368a4b1553dff0fc (do not edit this line) */
