/* Generated By:JJTree: Do not edit this line. ASTMultiplicative.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTMultiplicative extends SimpleNode {
  public ASTMultiplicative(int id) {
    super(id);
  }

  public ASTMultiplicative(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=295dbd532f5d770ea5c17d9e4c871391 (do not edit this line) */
