/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeMod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTMultiplicativeMod extends SimpleNode {
  public ASTMultiplicativeMod(int id) {
    super(id);
  }

  public ASTMultiplicativeMod(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=50ebf142719c01254a89ad931e7f04cc (do not edit this line) */
