/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeMult.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTMultiplicativeMult extends SimpleNode {
  public ASTMultiplicativeMult(int id) {
    super(id);
  }

  public ASTMultiplicativeMult(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=da0404b49f92aa5066146e97388dc4b7 (do not edit this line) */
