/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeDiv.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTMultiplicativeDiv extends SimpleNode {
  public ASTMultiplicativeDiv(int id) {
    super(id);
  }

  public ASTMultiplicativeDiv(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=29da482637193178adbe8dd07af2a033 (do not edit this line) */
