/* Generated By:JJTree: Do not edit this line. ASTRelationalLTE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTRelationalLTE extends SimpleNode {
  public ASTRelationalLTE(int id) {
    super(id);
  }

  public ASTRelationalLTE(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e9de62b5886c99a2c6353c438d7608dc (do not edit this line) */
