/* Generated By:JJTree: Do not edit this line. ASTRelationalLT.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTRelationalLT extends SimpleNode {
  public ASTRelationalLT(int id) {
    super(id);
  }

  public ASTRelationalLT(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ef7e4cff4021e136783e0cfe53feafbd (do not edit this line) */
