/* Generated By:JJTree: Do not edit this line. ASTRelationalGTE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTRelationalGTE extends SimpleNode {
  public ASTRelationalGTE(int id) {
    super(id);
  }

  public ASTRelationalGTE(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=41952bd4b68425ac5ffb2f7778ab8557 (do not edit this line) */
