/* Generated By:JJTree: Do not edit this line. ASTStatementGoto.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTStatementGoto extends SimpleNode {
  public ASTStatementGoto(int id) {
    super(id);
  }

  public ASTStatementGoto(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=29c6d4001f74f65076cd08316eed59ad (do not edit this line) */
