/* Generated By:JJTree: Do not edit this line. ASTStatementBreak.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTStatementBreak extends SimpleNode {
  public ASTStatementBreak(int id) {
    super(id);
  }

  public ASTStatementBreak(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=358779573d1a693ea2321d095d592391 (do not edit this line) */
