/* Generated By:JJTree: Do not edit this line. ASTStatementDoWhile.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTStatementDoWhile extends SimpleNode {
  public ASTStatementDoWhile(int id) {
    super(id);
  }

  public ASTStatementDoWhile(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=910a2a028ea49a42e4e455129e4fbc4e (do not edit this line) */
