/* Generated By:JJTree: Do not edit this line. ASTShiftLeft.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.serenegiant.lang.script;

public
class ASTShiftLeft extends SimpleNode {
  public ASTShiftLeft(int id) {
    super(id);
  }

  public ASTShiftLeft(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b91de595000def4fcf7891dfb8a7c7fa (do not edit this line) */
