/* Generated By:JavaCC: Do not edit this line. ScriptParserVisitor.java Version 6.1_2 */
package com.serenegiant.lang.script;

public interface ScriptParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTParse node, Object data);
  public Object visit(ASTCompoundStatement node, Object data);
  public Object visit(ASTStatementIf node, Object data);
  public Object visit(ASTStatementSwitch node, Object data);
  public Object visit(ASTStatementWhile node, Object data);
  public Object visit(ASTStatementDoWhile node, Object data);
  public Object visit(ASTStatementFor node, Object data);
  public Object visit(ASTForInitStatement node, Object data);
  public Object visit(ASTExpressionStatement node, Object data);
  public Object visit(ASTForUpdateStatement node, Object data);
  public Object visit(ASTStatementGoto node, Object data);
  public Object visit(ASTStatementContinue node, Object data);
  public Object visit(ASTStatementBreak node, Object data);
  public Object visit(ASTStatementReturn node, Object data);
  public Object visit(ASTConditional node, Object data);
  public Object visit(ASTConstant node, Object data);
  public Object visit(ASTLogicalOR node, Object data);
  public Object visit(ASTLogicalAND node, Object data);
  public Object visit(ASTInclusiveOR node, Object data);
  public Object visit(ASTExclusiveOR node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTEquality node, Object data);
  public Object visit(ASTNotEquality node, Object data);
  public Object visit(ASTRelationalLT node, Object data);
  public Object visit(ASTRelationalGT node, Object data);
  public Object visit(ASTRelationalLTE node, Object data);
  public Object visit(ASTRelationalGTE node, Object data);
  public Object visit(ASTShiftLeft node, Object data);
  public Object visit(ASTShiftRight node, Object data);
  public Object visit(ASTAdditivePlus node, Object data);
  public Object visit(ASTAdditiveMinus node, Object data);
  public Object visit(ASTMultiplicativeMult node, Object data);
  public Object visit(ASTMultiplicativeDiv node, Object data);
  public Object visit(ASTMultiplicativeMod node, Object data);
  public Object visit(ASTIdentifier node, Object data);
}
/* JavaCC - OriginalChecksum=b565feca6d2e0fb457821ace997f69dc (do not edit this line) */
