/* Generated By:JavaCC: Do not edit this line. ScriptParserVisitor.java Version 6.1_2 */
package com.serenegiant.lang.script;

public interface ScriptParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=5718c1b636e2254dbb0481868c5f4076 (do not edit this line) */
