/* Generated By:JJTree&JavaCC: Do not edit this line. ScriptParserConstants.java */
package com.serenegiant.lang.script;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 12;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 13;
  /** RegularExpression Id. */
  int HEX_LITERAL = 14;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 15;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 16;
  /** RegularExpression Id. */
  int EXPONENT = 17;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 18;
  /** RegularExpression Id. */
  int STRING_LITERAL = 19;
  /** RegularExpression Id. */
  int CONTINUE = 20;
  /** RegularExpression Id. */
  int VOLATILE = 21;
  /** RegularExpression Id. */
  int REGISTER = 22;
  /** RegularExpression Id. */
  int UNSIGNED = 23;
  /** RegularExpression Id. */
  int TYPEDEF = 24;
  /** RegularExpression Id. */
  int DFLT = 25;
  /** RegularExpression Id. */
  int DOUBLE = 26;
  /** RegularExpression Id. */
  int SIZEOF = 27;
  /** RegularExpression Id. */
  int SWITCH = 28;
  /** RegularExpression Id. */
  int RETURN = 29;
  /** RegularExpression Id. */
  int EXTERN = 30;
  /** RegularExpression Id. */
  int STRUCT = 31;
  /** RegularExpression Id. */
  int STATIC = 32;
  /** RegularExpression Id. */
  int SIGNED = 33;
  /** RegularExpression Id. */
  int WHILE = 34;
  /** RegularExpression Id. */
  int BREAK = 35;
  /** RegularExpression Id. */
  int UNION = 36;
  /** RegularExpression Id. */
  int CONST = 37;
  /** RegularExpression Id. */
  int FLOAT = 38;
  /** RegularExpression Id. */
  int SHORT = 39;
  /** RegularExpression Id. */
  int ELSE = 40;
  /** RegularExpression Id. */
  int CASE = 41;
  /** RegularExpression Id. */
  int LONG = 42;
  /** RegularExpression Id. */
  int ENUM = 43;
  /** RegularExpression Id. */
  int AUTO = 44;
  /** RegularExpression Id. */
  int VOID = 45;
  /** RegularExpression Id. */
  int CHAR = 46;
  /** RegularExpression Id. */
  int GOTO = 47;
  /** RegularExpression Id. */
  int FOR = 48;
  /** RegularExpression Id. */
  int INT = 49;
  /** RegularExpression Id. */
  int IF = 50;
  /** RegularExpression Id. */
  int DO = 51;
  /** RegularExpression Id. */
  int IDENTIFIER = 52;
  /** RegularExpression Id. */
  int LETTER = 53;
  /** RegularExpression Id. */
  int DIGIT = 54;
  /** RegularExpression Id. */
  int COMMA = 55;
  /** RegularExpression Id. */
  int QUESTION = 56;
  /** RegularExpression Id. */
  int ELLIPSIS = 57;
  /** RegularExpression Id. */
  int ASSIGN_EQ = 58;
  /** RegularExpression Id. */
  int MULT_EQ = 59;
  /** RegularExpression Id. */
  int DIV_EQ = 60;
  /** RegularExpression Id. */
  int MOD_EQ = 61;
  /** RegularExpression Id. */
  int PLUS_EQ = 62;
  /** RegularExpression Id. */
  int MINUS_EQ = 63;
  /** RegularExpression Id. */
  int SHIFT_LEFT_EQ = 64;
  /** RegularExpression Id. */
  int SHIFT_RIGHT_EQ = 65;
  /** RegularExpression Id. */
  int BIT_AND_EQ = 66;
  /** RegularExpression Id. */
  int BIT_XOR_EQ = 67;
  /** RegularExpression Id. */
  int BIT_OR_EQ = 68;
  /** RegularExpression Id. */
  int OR = 69;
  /** RegularExpression Id. */
  int AND = 70;
  /** RegularExpression Id. */
  int BIT_OR = 71;
  /** RegularExpression Id. */
  int BIT_XOR = 72;
  /** RegularExpression Id. */
  int AMPERSAND = 73;
  /** RegularExpression Id. */
  int EQ = 74;
  /** RegularExpression Id. */
  int NOT_EQ = 75;
  /** RegularExpression Id. */
  int LT = 76;
  /** RegularExpression Id. */
  int GT = 77;
  /** RegularExpression Id. */
  int LTE = 78;
  /** RegularExpression Id. */
  int GTE = 79;
  /** RegularExpression Id. */
  int SHIFT_LEFT = 80;
  /** RegularExpression Id. */
  int SHIFT_RIGHT = 81;
  /** RegularExpression Id. */
  int PLUS = 82;
  /** RegularExpression Id. */
  int MINUS = 83;
  /** RegularExpression Id. */
  int STAR = 84;
  /** RegularExpression Id. */
  int DIV = 85;
  /** RegularExpression Id. */
  int MOD = 86;
  /** RegularExpression Id. */
  int PLUSPLUS = 87;
  /** RegularExpression Id. */
  int MINUSMINUS = 88;
  /** RegularExpression Id. */
  int TILDE = 89;
  /** RegularExpression Id. */
  int NOT = 90;
  /** RegularExpression Id. */
  int DOT = 91;
  /** RegularExpression Id. */
  int POINTERTO = 92;
  /** RegularExpression Id. */
  int DOTSTAR = 93;
  /** RegularExpression Id. */
  int ARROWSTAR = 94;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int PREPROCESSOR_OUTPUT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"#\"",
    "\"\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 11>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"continue\"",
    "\"volatile\"",
    "\"register\"",
    "\"unsigned\"",
    "\"typedef\"",
    "\"default\"",
    "\"double\"",
    "\"sizeof\"",
    "\"switch\"",
    "\"return\"",
    "\"extern\"",
    "\"struct\"",
    "\"static\"",
    "\"signed\"",
    "\"while\"",
    "\"break\"",
    "\"union\"",
    "\"const\"",
    "\"float\"",
    "\"short\"",
    "\"else\"",
    "\"case\"",
    "\"long\"",
    "\"enum\"",
    "\"auto\"",
    "\"void\"",
    "\"char\"",
    "\"goto\"",
    "\"for\"",
    "\"int\"",
    "\"if\"",
    "\"do\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\":\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
  };

}
