/* Generated By:JavaCC: Do not edit this line. ScriptParserVisitor.java Version 6.1_2 */
package com.serenegiant.lang.script;

public interface ScriptParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTParse node, Object data);
  public Object visit(ASTStatementIf node, Object data);
  public Object visit(ASTStatementSwitch node, Object data);
  public Object visit(ASTStatementWhile node, Object data);
  public Object visit(ASTStatementDoWhile node, Object data);
  public Object visit(ASTForInitStatement node, Object data);
  public Object visit(ASTExpressionStatement node, Object data);
  public Object visit(ASTForUpdateStatement node, Object data);
  public Object visit(ASTConditional node, Object data);
  public Object visit(ASTConstant node, Object data);
  public Object visit(ASTLogicalOR node, Object data);
  public Object visit(ASTLogicalAND node, Object data);
  public Object visit(ASTInclusiveOR node, Object data);
  public Object visit(ASTExclusiveOR node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTEquality node, Object data);
  public Object visit(ASTNotEquality node, Object data);
  public Object visit(ASTRelationalLT node, Object data);
  public Object visit(ASTRelationalGT node, Object data);
  public Object visit(ASTRelationalLTE node, Object data);
  public Object visit(ASTRelationalGTE node, Object data);
  public Object visit(ASTShiftLeft node, Object data);
  public Object visit(ASTShiftRight node, Object data);
  public Object visit(ASTAdditivePlus node, Object data);
  public Object visit(ASTAdditiveMinus node, Object data);
  public Object visit(ASTMultiplicative node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTIntegerConst node, Object data);
  public Object visit(ASTFloatConst node, Object data);
  public Object visit(ASTCharConst node, Object data);
  public Object visit(ASTStringConst node, Object data);
}
/* JavaCC - OriginalChecksum=99483119702f29de50fd9d4c4019174f (do not edit this line) */
